/* ============================================================
   CREATE LEADS TABLE
   ============================================================ */

CREATE TABLE leads (

    id INT UNSIGNED NOT NULL AUTO_INCREMENT,

    /*
     * Internal lead reference.
     * Generated by PHP.
     *
     * Example:
     * LD-20260830-0001
     */

    lead_code VARCHAR(50) NOT NULL,


    /*
     * Lead basic information.
     */

    name VARCHAR(150) NOT NULL,

    company VARCHAR(150) DEFAULT NULL,

    phone VARCHAR(30) DEFAULT NULL,

    email VARCHAR(150) DEFAULT NULL,


    /*
     * Service requested by the lead.
     */

    service VARCHAR(150) DEFAULT NULL,


    /*
     * Lead source.
     *
     * Values used by the current leads.php:
     *
     * website
     * whatsapp
     * referral
     * social_media
     * direct
     * other
     */

    source VARCHAR(100) DEFAULT NULL,


    /*
     * Lead pipeline status.
     */

    status ENUM(
        'new',
        'contacted',
        'follow_up',
        'proposal_sent',
        'negotiation',
        'won',
        'lost'
    ) NOT NULL DEFAULT 'new',


    /*
     * Lead priority.
     */

    priority ENUM(
        'low',
        'medium',
        'high'
    ) NOT NULL DEFAULT 'medium',


    /*
     * Follow-up date.
     */

    follow_up_date DATE DEFAULT NULL,


    /*
     * Additional notes.
     */

    notes TEXT DEFAULT NULL,


    /*
     * Record timestamps.
     */

    created_at TIMESTAMP NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP NOT NULL
        DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,


    /*
     * Primary key.
     */

    PRIMARY KEY (id),


    /*
     * Lead code must be unique.
     */

    UNIQUE KEY uq_lead_code (
        lead_code
    ),


    /*
     * Search indexes.
     */

    KEY idx_lead_name (
        name
    ),

    KEY idx_lead_company (
        company
    ),

    KEY idx_lead_phone (
        phone
    ),

    KEY idx_lead_email (
        email
    ),

    KEY idx_lead_status (
        status
    ),

    KEY idx_lead_priority (
        priority
    ),

    KEY idx_lead_source (
        source
    ),

    KEY idx_lead_follow_up (
        follow_up_date
    ),

    KEY idx_lead_created_at (
        created_at
    )

)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci;


/* ============================================================
   SAMPLE LEADS
   ============================================================ */

INSERT INTO leads
(
    lead_code,
    name,
    company,
    phone,
    email,
    service,
    source,
    status,
    priority,
    follow_up_date,
    notes
)
VALUES

(
    'LD-20260830-0001',
    'Ravi Kumar',
    'Sri Lakshmi Traders',
    '9876543210',
    'ravi@example.com',
    'Website Development',
    'website',
    'new',
    'high',
    '2026-09-02',
    'Interested in a business website.'
),

(
    'LD-20260830-0002',
    'Priya Reddy',
    'Puttur Fashion Store',
    '9876543211',
    'priya@example.com',
    'Digital Marketing',
    'referral',
    'contacted',
    'medium',
    '2026-09-04',
    'Discussed social media marketing.'
),

(
    'LD-20260830-0003',
    'Arun Kumar',
    'Tirupati Electronics',
    '9876543212',
    'arun@example.com',
    'E-commerce Website',
    'whatsapp',
    'follow_up',
    'high',
    '2026-09-05',
    'Follow up regarding ecommerce quotation.'
),

(
    'LD-20260830-0004',
    'Sneha Sharma',
    'Success Consultancy',
    '9876543213',
    'sneha@example.com',
    'SEO',
    'social_media',
    'proposal_sent',
    'medium',
    '2026-09-07',
    'Proposal sent. Waiting for response.'
),

(
    'LD-20260830-0005',
    'Venkatesh Rao',
    'Puttur Restaurant',
    '9876543214',
    'venkatesh@example.com',
    'Website + SEO',
    'direct',
    'negotiation',
    'high',
    '2026-09-03',
    'Negotiating final project price.'
),

(
    'LD-20260830-0006',
    'Kiran',
    'KKC Institutions',
    '9876543215',
    'kiran@example.com',
    'Web Application',
    'referral',
    'won',
    'high',
    NULL,
    'Project confirmed.'
),

(
    'LD-20260830-0007',
    'Manoj',
    'Local Hardware Store',
    '9876543216',
    'manoj@example.com',
    'Website Development',
    'direct',
    'lost',
    'low',
    NULL,
    'Client decided not to proceed.'
);